notifications:
    - id: gotify-notice
      type: gotify
      data:
        url: ENC[AES256_GCM,data:7wESRrU6rkDZ/muSAmg/IfzF4ppEMjHrwSKtrpE=,iv:6dBtlf3YF8akoOw9vRefuwZ7A+8E7LeNfeUTaoNwTvc=,tag:HA2F2thfpDcnSOgnm/8zYQ==,type:str]
        token: ENC[AES256_GCM,data:CAcftnkwbmn6qTGTY4EQ,iv:tKIn52aR+UzMc5NMA6a1Inyoia4i1/wLjbpMs+ILWJc=,tag:kPzI7zUHyAG+Zr7ZPECnOg==,type:str]
    - id: discord
      type: discord
      data:
        url: ENC[AES256_GCM,data:LYNQt+rbZCljQvxTKVZTh1EAWtSp3X0xlvscJ8xp3NoL8Gg2cErGbXE8qk2vEonABt85dAxsenj3TsmxItay1qBdHNEe0pSBTf9xwYJXSTrGOCEeQwH7vG5oNykNF0lKvwkOA3Wkcrs+T/3MpgFSGHpHQ2IwZIE/aQ==,iv:BdrFf3CTmXfHxiM2Zxmx1NOdFugnvskywKtu1bOJJrE=,tag:3uMdALuyEfUx/GXp/ym2Bg==,type:str]
probes:
    - id: "1"
      name: Adguardhome
      description: ""
      interval: 60
      requests:
        - url: https://adguard.timmybtech.com
          body: {}
          timeout: 10000
          headers: {}
          method: GET
          alerts: []
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status < 200 or response.status > 299
          message: Target is not healthy. It has not been returning status code 2xx.
        - assertion: response.time > 2000
          message: Target is not healthy. The response time has been greater than 2000 ms.
    - id: "2"
      name: Adguardhome Replica
      description: ""
      interval: 60
      requests:
        - url: https://adguard2.timmybtech.com
          body: {}
          timeout: 10000
          headers: {}
          method: GET
          alerts: []
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status < 200 or response.status > 299
          message: Target is not healthy. It has not been returning status code 2xx.
        - assertion: response.time > 2000
          message: Target is not healthy. The response time has been greater than 2000 ms.
    - id: "3"
      name: blog.timothybryantjr
      description: ""
      interval: 60
      requests:
        - url: https://blog.timothybryantjr.com
          body: {}
          timeout: 10000
          headers: {}
          method: GET
          alerts: []
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status < 200 or response.status > 299
          message: Target is not healthy. It has not been returning status code 2xx.
        - assertion: response.time > 2000
          message: Target is not healthy. The response time has been greater than 2000 ms.
    - id: "4"
      name: bryantnas
      description: Check if bryantnas is up
      interval: 60
      requests:
        - url: nas.timmybtech.com
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: bryantnas is down
    - id: "5"
      name: ct102 (syncthing)
      description: Check if ct102 (syncthing) is up
      interval: 60
      requests:
        - url: syncthing.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: ct102 (syncthing) is down
    - id: "6"
      name: Gitea
      description: ""
      interval: 60
      requests:
        - url: https://gitea.local.timmybtech.com/
          body: {}
          timeout: 10000
          headers: {}
          method: GET
          alerts: []
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status < 200 or response.status > 299
          message: Target is not healthy. It has not been returning status code 2xx.
        - assertion: response.time > 2000
          message: Target is not healthy. The response time has been greater than 2000 ms.
    - id: "7"
      name: Grafana
      description: ""
      interval: 60
      requests:
        - url: https://grafana.local.timmybtech.com
          body: {}
          timeout: 10000
          headers: {}
          method: GET
          alerts: []
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status < 200 or response.status > 299
          message: Target is not healthy. It has not been returning status code 2xx.
        - assertion: response.time > 2000
          message: Target is not healthy. The response time has been greater than 2000 ms.
    - id: "8"
      name: homeassistant
      description: Check if homeassistant is up
      interval: 60
      requests:
        - url: hass.timmybtech.com
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: homeassistant is down
    - id: "9"
      name: homepage.timothybryantjr
      description: ""
      interval: 60
      requests:
        - url: https://timothybryantjr.com
          body: {}
          timeout: 10000
          headers: {}
          method: GET
          alerts: []
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status < 200 or response.status > 299
          message: Target is not healthy. It has not been returning status code 2xx.
        - assertion: response.time > 2000
          message: Target is not healthy. The response time has been greater than 2000 ms.
    - id: "10"
      name: homelab-oci03
      description: Check if homelab-oci03 is up
      interval: 60
      requests:
        - url: homelab-oci03.local.lan
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: homelab-oci03 is down
    - id: "11"
      name: k3s-0
      description: Check if k3s-0 is up
      interval: 60
      requests:
        - url: k3s-0.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: k3s-0 is down
    - id: "12"
      name: k3s-0-worker
      description: Check if k3s-0-worker is up
      interval: 60
      requests:
        - url: k3s-0-worker.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: k3s-0-worker is down
    - id: "13"
      name: k3s-1
      description: Check if k3s-1 is up
      interval: 60
      requests:
        - url: k3s-1.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: k3s-1 is down
    - id: "14"
      name: k3s-1-worker
      description: Check if k3s-1-worker is up
      interval: 60
      requests:
        - url: k3s-1-worker.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: k3s-1-worker is down
    - id: "15"
      name: k3s-2
      description: Check if k3s-2 is up
      interval: 60
      requests:
        - url: k3s-2.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: k3s-2 is down
    - id: "16"
      name: k3s-2-worker
      description: Check if k3s-2-worker is up
      interval: 60
      requests:
        - url: k3s-2-worker.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: k3s-2-worker is down
    - id: "17"
      name: LinkAce
      description: ""
      interval: 60
      requests:
        - url: https://linkace.timmybtech.com
          body: {}
          timeout: 10000
          headers: {}
          method: GET
          alerts: []
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status < 200 or response.status > 299
          message: Target is not healthy. It has not been returning status code 2xx.
        - assertion: response.time > 2000
          message: Target is not healthy. The response time has been greater than 2000 ms.
    - id: "18"
      name: pihole2
      description: Check if pihole2 is up
      interval: 60
      requests:
        - url: pihole2.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: pihole2 is down
    - id: "19"
      name: Prometheus
      description: ""
      interval: 60
      requests:
        - url: https://prometheus.local.timmybtech.com
          body: {}
          timeout: 10000
          headers: {}
          method: GET
          alerts: []
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status < 200 or response.status > 299
          message: Target is not healthy. It has not been returning status code 2xx.
        - assertion: response.time > 2000
          message: Target is not healthy. The response time has been greater than 2000 ms.
    - id: "20"
      name: pve2
      description: Check if pve2 is up
      interval: 60
      requests:
        - url: pve2.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: pve2 is down
    - id: "21"
      name: pve3
      description: Check if pve3 is up
      interval: 60
      requests:
        - url: pve3.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: pve3 is down
    - id: "22"
      name: raspberrypi
      description: Check if raspberrypi is up
      interval: 60
      requests:
        - url: raspberrypi.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: raspberrypi is down
    - id: "23"
      name: subnet-router
      description: Check if subnet-router is up
      interval: 60
      requests:
        - url: subnet-router.tailebee.ts.net
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: subnet-router is down
    - id: "24"
      name: timothy-hp-laptop
      description: Check if timothy-hp-laptop is up
      interval: 60
      requests:
        - url: timothy-hp-laptop.tailebee.ts.net.
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: timothy-hp-laptop is down
    - id: "25"
      name: vm303
      description: Check if vm303 is up
      interval: 60
      requests:
        - url: vm303.local.lan
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: vm303 is down
    - id: "26"
      name: vm304
      description: Check if vm304 is up
      interval: 60
      requests:
        - url: vm304.local.lan
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: vm304 is down
    - id: "27"
      name: vm305
      description: Check if vm305 is up
      interval: 60
      requests:
        - url: vm305.local.lan
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: vm305 is down
    - id: "28"
      name: vm306
      description: Check if vm306 is up
      interval: 60
      requests:
        - url: vm306.local.lan
          ping: true
          alerts:
            - assertion: response.status != 200
              message: Status code is not 200
            - assertion: response.time > 2000
              message: Request took more than 2 seconds
      incidentThreshold: 10
      recoveryThreshold: 10
      alerts:
        - assertion: response.status != 200
          message: vm306 is down
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WVNkS3VxeXBlWTVQMEJU
            cDhGNHhiakxYNUNIbXd1alFEWkIvR1pGRjM0Cis5QndjWk5RenFDQUhpUjMrcXNa
            b2NNVXhUV04waTJMUzhTbHI2SjRzdjAKLS0tIGJ0NnduYjdCeXB0ZmV0R3k5VnF2
            M0hlOEZOMmdpcGRDNnRXNDJ5MkIycjAKsxoFfwnbSmPbnsTWbZarHCsPsT7ardPS
            hX/4dAd7brRXdse+FYzel8zedoP2xlCyEXR8HXevffZ3ph2WGsqwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T04:53:56Z"
    mac: ENC[AES256_GCM,data:kTQftLgdE2ORRCnryjNOZQ1qZZk/olYxRb0RZ96vFBeo/q+KV9CnvE4BkUMWm05XwiObgFJUqWa56VQQhJ3t0Mg8m1tJsmeYeWCJx+9aSrv7nD04YgllYYrQVf6dD+5KpaMIqczrSFYs6VqTTV4xbbV+sf6gp4TRY+dXvwcsJwQ=,iv:VZsYNHdjUj3YF/qpDgqSw7xzj52TQhlXoUglVHyHjoE=,tag:65uG/B5sRbmBgCZBbDpTZg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.1
