notifications:
    - id: gotify-notice
      type: gotify
      data:
        url: ENC[AES256_GCM,data:eKAv7kYvq6b4dBlUhbQvydFJYZ9qKGzOvEmGFh8=,iv:zdDA7DpLItKcftckZGhz2n0bAMSFiJ3ASElyekfpcok=,tag:OLEyJnYds8wa10+bcubucg==,type:str]
        token: ENC[AES256_GCM,data:rscmHSho2XkBwtZg6ny9,iv:ErrkJXs/K3PTXuip3adzX3yDQoOp48Xd2JTWuupaw3E=,tag:axKt5vePjvrcGofAGqCWRQ==,type:str]
    - id: discord
      type: discord
      data:
        url: ENC[AES256_GCM,data:McnQlBv3SLrhL2cU8rfDj3/Qg2+CWYXnKaHrmMC9Y2cot8IG/VJePUGtBHpfWcydHZKDixrEOYLtFgudlLz9p1/VHRifM9lOPHr7bINii+DmZE5WUcjVwbB4wkwXBWBLLa4XPObgWGXIlF/bgoPxws0T1rd5FrkzuA==,iv:BMVHc6eMIQURxG+QRxQ/5i/DoxW558AbX5iIFdUTL2c=,tag:NpyqQm3qoKoUI92Q9Hdi4g==,type:str]
probes:
    - id: homelab-pg
      name: homelab pg database health
      description: ensure db health
      # in seconds
      interval: 60
      incidentThreshold: 2
      recoveryThreshold: 2
      postgres:
        - uri: ENC[AES256_GCM,data:IFLWtaF4ePr8XHx0iyUETmA5S4aGr/9rnj0uTxXdN7nDFTcVHLmw14uH6npcPQtwhLS5s8sHCal0xAGOLiJP,iv:kph0z78O0cyTAidsNWQSnaq+Lipgoke5p+ChSVcFzIM=,tag:FcIljr2qBvvQvyKDZokAOw==,type:str]
      alerts:
        # in milliseconds
        - assertion: response.time > 10000
          message: Postgres response is slow, took {{ response.time }}ms
    - id: docker-oci-pg
      name: docker pg database health
      description: ensure db health
      # in seconds
      interval: 60
      incidentThreshold: 2
      recoveryThreshold: 2
      postgres:
        - uri: ENC[AES256_GCM,data:WjZ0jATvz0DTu8YWMGoc4igM4pBugAMmWPhYX7xFCAvLp8z6oPUIZpL0ybKQKoLQtmP5N3lYucySbk3dzw7eUI1fjU4=,iv:06A7vzyEVID0sI9AYCI8SN7102zp19Ot/iiJYxzOIc4=,tag:1f2leN03papU4YT+l/yM0w==,type:str]
      alerts:
        # in milliseconds
        - assertion: response.time > 10000
          message: Postgres response is slow, took {{ response.time }}ms
    - id: homelab-mysql
      name: mysql database health
      description: ensure db health
      mysql:
        - host: ENC[AES256_GCM,data:+BXzQnupg2EpAcdvr1/Y,iv:3pj/lD8Ik99+tvx0dFMk0gFnJA/A8Whuh801go1V16s=,tag:ZcTALCcse9QgszPxI2GZFg==,type:str]
          port: ENC[AES256_GCM,data:4VdU3A==,iv:teT4aAR1kws76itIQbyhQi4JEnuooqpm3uopdrVIZLk=,tag:MbrAfBLGcsZ7PeOsCQmK8Q==,type:int]
          database: ENC[AES256_GCM,data:6Z1Dw+w=,iv:zke4nLPzrVJCV/eOm1fYQEEzXnn7kxONa2Zl7He12YY=,tag:nFM5MLQYrJFxMryXRQny/g==,type:str]
          username: ENC[AES256_GCM,data:Q4f6Pciszg==,iv:ssscDXUDEtkiqhbRRTWJLf9ubEJMhu8lKSNTOges94E=,tag:nEy7nQ/tZ6zFZZfa3zDWxA==,type:str]
          password: ENC[AES256_GCM,data:GOMrEsEfqpv55YEL,iv:airm81M4DzvdvO5YDV40uW7CSJlBxcdVLGONhdybUpc=,tag:cyVWzQcc2l0sh40ajsLJ+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MDFTMmQvR21sTmxIaHJh
            VlpVVk5zbFpRQ1RBNm5SaXVyVkJQSjJFV0c0CmR1S0xpMnFmdTcvVi9vbWxvNW15
            RW5vSkxHVHN6ZGFRNFhZWlI2QVNaaE0KLS0tIEdPcTB6MDJ0eUV6Wk50SXZWYzE3
            dFhUdHdFRkJzc2I5VGxOQ01NSy9kQU0K+aVdG5uFWdMbe3wC+fhkagFlVJyw0iwu
            zFXpuM1hOf83R+O3C1yVjLhn6GJiW3ORfmUev6uqgQlpau0RLPZORw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T04:55:36Z"
    mac: ENC[AES256_GCM,data:sWR7tAAAU4nRy7RZj36ADJP6w2SPSzLb0Gf7jB17m6TzyEHyaI+c5Jurw6ThZbpH8wz1Kslu4WyrRq8gDi6Rymey5nWbVgb+NU6zKlXrbZXWeHt0FeeOAPlGxuDVKZ9f5F1CaZvvB7EGJb4uQkC+te9+oDchCmThXrcZgFwIBKI=,iv:YJkdXtUtQqHvSBv9B7tUbALB4jSRCdpd015h4fJ3rbs=,tag:MQP05Yu6lwXMB9+uHOa+Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|postgres|mysql)$
    version: 3.8.1
