name: Publish Docker Images

on:
  pull_request:
    branches:
      - main
    paths:
      - "python/aws_usage_cost/**"
      - "python/bills_reminder_sms/**"
      - "python/oci_usage_cost/**"

jobs:
  Docker-Publish:
    environment:
      name: production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "python/aws_usage_cost"
          - "python/bills_reminder_sms"
          - "python/oci_usage_cost"

    steps:
      - name: Pull git repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.path }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.path }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
